%% UpdateSnapshotFromExcel.m
% =========================================================================
% Extracts matched Angle, Power, and Visualize values generated by Excel
% formulas and updates the fast-loading .mat GUI snapshot, keeping them
% associated with the correct Animal ID and Date.
%
% Built to synchronize manual Angle and Power inputs (via XLOOKUP) and
% the Visualize flag (computed formula) with the automatically processed
% data from Batch_Processing.m script.
% =========================================================================

clc; clear;

% ── Configuration ────────────────────────────────────────────────────────
excelFile    = 'Batch_Analysis_Results.xlsx';
sheetName    = 'ProcessedResults';
snapshotFile = 'Batch_Analysis_Results_Snapshot.mat';
% ─────────────────────────────────────────────────────────────────────────

fprintf('1. Loading data from Excel: %s (Sheet: %s)...\n', excelFile, sheetName);
try
    % Read the processed results sheet
    % By default, readtable retrieves the evaluated values of formulas, not the formula text.
    opts = detectImportOptions(excelFile, 'Sheet', sheetName, 'VariableNamingRule', 'preserve');
    excelData = readtable(excelFile, opts, 'Sheet', sheetName);
    
    % Ensure column names are standardized
    excelData.Properties.VariableNames = matlab.lang.makeValidName(excelData.Properties.VariableNames);
catch ME
    warning('Failed to load Excel file. Make sure the file is CLOSED in Excel.\n%s', ME.message);
    return;
end

fprintf('2. Loading GUI snapshot: %s...\n', snapshotFile);
if ~isfile(snapshotFile)
    warning('Snapshot file not found: %s', snapshotFile);
    return;
end

% Load the .mat file (Your process saves 'T' and 'lastUpdated')
load(snapshotFile, 'T', 'lastUpdated');

if ~exist('T', 'var')
    warning('The loaded snapshot does not contain the expected data table "T".');
    return;
end

fprintf('3. Synchronizing Angle, Power, and Visualize values...\n');

% ── FORMAT STANDARDIZATION (ID and Date) ─────────────────────────────────
% Convert IDs to standard string arrays for robust comparison
excelIDs = string(excelData.ID);
guiIDs   = string(T.ID);

% Convert Dates to standard datetime arrays for robust comparison
% Handle Excel dates
if isdatetime(excelData.Date)
    excelDates = dateshift(excelData.Date, 'start', 'day'); 
else
    excelDates = datetime(string(excelData.Date), 'InputFormat', 'yyyy-MM-dd');
end

% Handle Snapshot dates
if isdatetime(T.Date)
    guiDates = dateshift(T.Date, 'start', 'day');
else
    guiDates = datetime(string(T.Date), 'InputFormat', 'yyyy-MM-dd');
end

% Handle Angle and Power (may have XLOOKUP errors like "Not Found" or "#N/A")
% This safely converts the columns to double, setting errors/text to NaN
if iscell(excelData.Angle) || isstring(excelData.Angle)
    excelAngleNum = str2double(string(excelData.Angle));
else
    excelAngleNum = double(excelData.Angle);
end

if iscell(excelData.Power) || isstring(excelData.Power)
    excelPowerNum = str2double(string(excelData.Power));
else
    excelPowerNum = double(excelData.Power);
end

% Handle Visualize as boolean (formula result: TRUE/FALSE)
if isnumeric(excelData.Visualize)
    excelVisualize = logical(excelData.Visualize);
elseif islogical(excelData.Visualize)
    excelVisualize = excelData.Visualize;
else
    % Handle string/cell representation
    excelVisualize = strcmpi(string(excelData.Visualize), 'true') | ...
                     strcmpi(string(excelData.Visualize), '1');
end

% ── MATCHING AND UPDATING LOOP ───────────────────────────────────────────
updatedCount = 0;

for i = 1:height(T)
    currentID   = guiIDs(i);
    currentDate = guiDates(i);
    
    % Find the matching row index in the Excel table (Match both ID & Date)
    matchIdx = find((excelIDs == currentID) & (excelDates == currentDate), 1);
    
    if ~isempty(matchIdx)
        % Retrieve values from Excel arrays
        newAngle = excelAngleNum(matchIdx);
        newPower = excelPowerNum(matchIdx);
        newVisualize = excelVisualize(matchIdx);
        
        % Overwrite the values in the snapshot table
        T.Angle(i) = newAngle;
        T.Power(i) = newPower;
        T.Visualize(i) = newVisualize;
        
        updatedCount = updatedCount + 1;
    end
end

% ── SAVE BACK TO FILE ────────────────────────────────────────────────────
% Update the timestamp
lastUpdated = datetime('now');

% Save the updated table back to the binary .mat file
fprintf('4. Saving updated snapshot back to %s...\n', snapshotFile);
save(snapshotFile, 'T', 'lastUpdated');

fprintf('------------------------------------------------------------------\n');
fprintf('SUCCESS! Synchronized %d records (Angle, Power, Visualize) from Excel to .mat snapshot.\n', updatedCount);
fprintf('You can now open your GUI.\n');